/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
    public static inline var Puzzle:String = "event:/Music/Puzzle";
}

class FmodSFX {
    public static inline var Announcer_4:String = "event:/SFX/Announcer/Announcer_4";
    public static inline var Announcer_5:String = "event:/SFX/Announcer/Announcer_5";
    public static inline var Announcer_6:String = "event:/SFX/Announcer/Announcer_6";
    public static inline var Announcer_7:String = "event:/SFX/Announcer/Announcer_7";
    public static inline var Announcer_8:String = "event:/SFX/Announcer/Announcer_8";
    public static inline var Announcer_9:String = "event:/SFX/Announcer/Announcer_9";
    public static inline var AnnouncerBad:String = "event:/SFX/Announcer/AnnouncerBad";
    public static inline var AnnouncerGood:String = "event:/SFX/Announcer/AnnouncerGood";
    public static inline var AnnouncerWorse:String = "event:/SFX/Announcer/AnnouncerWorse";
    public static inline var CursorMove:String = "event:/SFX/Cursor/CursorMove";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var TileCannotRotate:String = "event:/SFX/Tiles/TileCannotRotate";
    public static inline var TileClear:String = "event:/SFX/Tiles/TileClear";
    public static inline var TileClockwise:String = "event:/SFX/Tiles/TileClockwise";
    public static inline var TileCounterclockwise:String = "event:/SFX/Tiles/TileCounterclockwise";
    public static inline var TileSlide:String = "event:/SFX/Tiles/TileSlide";
    public static inline var TileSlide2:String = "event:/SFX/Tiles/TileSlide2";
}
