/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
    public static inline var Puzzle:String = "event:/Music/Puzzle";
}

class FmodSFX {
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var TileClockwise:String = "event:/SFX/Tiles/TileClockwise";
    public static inline var TileCounterclockwise:String = "event:/SFX/Tiles/TileCounterclockwise";
}
